all:block unblock count run
block:
	gcc -o sbx421_block sbx421_block.c
unblock:
	gcc -o sbx421_unblock sbx421_unblock.c
count:
	gcc -o sbx421_count sbx421_count.c
run:
	g++ -o sbx421_run sbx421_run.cpp -std=c++11
clean:
	rm sbx421_run sbx421_count sbx421_unblock sbx421_block